{% set name = "django-treebeard" %}
{% set version = "4.5.1" %}
{% set sha256 = "80150017725239702054e5fa64dc66e383dc13ac262c8d47ee5a82cb005969da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8

test:
  imports:
    - treebeard

about:
  home: https://github.com/django-treebeard/django-treebeard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Efficient tree implementations for Django
  description: |
    django-treebeard is a library that implements efficient 
    tree implementations for the Django Web Framework 1.8 and later.
  doc_url: http://django-treebeard.readthedocs.io/en/latest/
  dev_url: https://github.com/django-treebeard/django-treebeard

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
