{% set name = "django-treebeard" %}
{% set version = "5.0.1" %}
{% set sha256 = "7967e0e67c5c984991b10dcd2bd6987c5ec0c88aa1f0f40583b2b05004222082" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - treebeard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-treebeard/django-treebeard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Efficient tree implementations for Django
  description: |
    django-treebeard is a library that implements efficient
    tree implementations for the Django Web Framework 1.8 and later.
  doc_url: http://django-treebeard.readthedocs.io/en/latest/
  dev_url: https://github.com/django-treebeard/django-treebeard

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
